pull_request_rules:
  # approve
  - name: automatic approval
    conditions:
      - author=dsm23
      - check-success=pr-title
    actions:
      review:
        type: APPROVE
        message: Automatically approving dsm23
  - name: automatic approval for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=pr-title
    actions:
      review:
        type: APPROVE
        message: Automatically approving renovate
  # merge
  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
      - check-success=pr-title
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  # delete
  - name: automatic deletion of head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
